name: Build for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Create .love file
      run: zip -7 -r game.love main.lua assets lib README.md LICENSES LICENSE

    - name: Set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | sdkmanager --licenses

    - name: Install NDK
      run: |
        sdkmanager --install "ndk;25.2.9519653"
        echo "NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

    - name: Build Android APK
      uses: love-actions/love-actions-android@v2
      with:
        love_file: game.love  # Nombre del archivo .love que será generado y compilado
        version_code: 1
        version_name: '1.0.0'
        package: 'com.example.trianglesolver'
        resource-path: "./"
        key_store: ${{ secrets.ANDROID_KEY_STORE }}
        key_alias: ${{ secrets.ANDROID_KEY_ALIAS }}
        key_store_password: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
        key_password: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: triangle-solver-apk
        path: build/app/outputs/apk/release/app-release.apk