name: Build for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Create .love file
      run: zip -7 -r game.love main.lua assets lib README.md LICENSES LICENSE

    - name: Build Android APK
      uses: love-actions/love-actions-android@v2
      with:
        love_file: game.love  # Nombre del archivo .love que será generado y compilado
        version_code: 1
        version_name: '1.0.0'
        package: 'com.example.trianglesolver'
        resource-path: "./assets"
        key_store: ${{ secrets.ANDROID_KEY_STORE }}
        key_alias: ${{ secrets.ANDROID_KEY_ALIAS }}
        key_store_password: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
        key_password: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: triangle-solver-apk
        path: build/app/outputs/apk/release/app-release.apk