name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create .love file
      run: zip -9 -r triangle-solver.love main.lua assets libs

    - name: Upload .love file
      uses: actions/upload-artifact@v2
      with:
        name: triangle-solver
        path: triangle-solver.love